name: Build
on: 
  push: 
      branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 22.x
      - name: Install Angular 17
        run: npm install -g @angular/cli@17.3.8
      - name: Install Ionic
        run: npm install -g @ionic/cli@7.2.0

      - name: npm Install
        run: npm install
        
      - name: Build Ionic web
        run: npm run build
        
      - name: Rename folder
        run: mv www pokedex-ionic
        
      - name: Delete folder 
        run: rm -f www

      - name: Remove files except "pokedex-ionic"
        run: |
          find . -maxdepth 1 ! -name 'pokedex-ionic' ! -name '.' -exec rm -rf {} 
        
      - name: Commit and Push build
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Publish build
          branch: build
          commit_user_name: Jaime Munoz "github-actions[bot]"
          commit_user_email: jaime.munoz200@gmail.com
          commit_author: Jaime200
          add_options: 'pokedex-ionic'
          commit_options: '--amend --no-edit'
          push_options: '--force'
          create_branch: true
